version: '3.9'
services:
  app:
    build:
      context: .
      target: dev
    command: npm run dev -- --host 0.0.0.0 --port 4321
    ports:
      - '4321:4321'
    environment:
      STATUS_OVERRIDE: ''
      PUBLIC_SPOTIFY_EMBED_URL: ''
    volumes:
      - .:/app
      - /app/node_modules
